[book]
authors = ["rouzbehsbz"]
language = "en"
multilingual = false
src = "src"
title = "برنامه نویسی Async در زبان Rust"

[output.html]
default-theme = "rust"
copy-fonts = true
additional-css = ["theme/custom.css"]

[output.html.font]
enable = true
woff = true